#!/usr/bin/env python3
"""One-shot: add missing merchant-role (coalitions/clearinghouse/gifting) keys to ar.json + en.json.
Appends keys before the closing brace, preserving existing file bytes/formatting."""
import json
import sys

AR = {
    "clearinghouse_action": "الإجراء",
    "clearinghouse_date": "التاريخ",
    "clearinghouse_detailed_ledger": "السجل التفصيلي",
    "clearinghouse_from": "من",
    "clearinghouse_how_step_1": "راجع ملخص النقاط المصدرة والمستردة بين أعضاء الائتلاف",
    "clearinghouse_how_step_2": "تحقق من صافي الرصيد المستحق لكل عضو",
    "clearinghouse_how_step_3": "اضغط تسوية لتأكيد تحويل الصافي بين الأعضاء",
    "clearinghouse_how_step_4": "تظهر التسوية المؤكدة في السجل التفصيلي",
    "clearinghouse_how_title": "كيف تستخدم غرفة المقاصة؟",
    "clearinghouse_internal_only_disclosure": "هذه البيانات داخلية لأعضاء الائتلاف فقط ولا تظهر للعملاء",
    "clearinghouse_net": "الصافي",
    "clearinghouse_no_ledger": "لا توجد حركات في السجل بعد",
    "clearinghouse_refresh": "تحديث",
    "clearinghouse_settle": "تسوية",
    "clearinghouse_settlement_confirmed": "تم تأكيد التسوية بنجاح",
    "clearinghouse_summary_cross_redemptions": "الاستردادات المتقاطعة",
    "clearinghouse_summary_net_balance": "صافي الرصيد",
    "clearinghouse_summary_points_issued": "النقاط المصدرة",
    "clearinghouse_to": "إلى",
    "coalition_accept": "قبول",
    "coalition_activity_unknown": "نشاط غير معروف",
    "coalition_cancel": "إلغاء",
    "coalition_create_and_invite": "إنشاء ودعوة",
    "coalition_create_help": "أنشئ ائتلافاً خاصاً وادعُ تجاراً قريبين للانضمام إليه",
    "coalition_create_invitees_hint": "أدخل معرف التاجر أو رقم هاتفه",
    "coalition_create_invitees_label": "المدعوون",
    "coalition_create_invitees_range": "يمكنك دعوة من 1 إلى 10 تجار",
    "coalition_create_missing_id": "أدخل معرف التاجر أولاً",
    "coalition_create_name_label": "اسم الائتلاف",
    "coalition_create_name_required": "اسم الائتلاف مطلوب",
    "coalition_create_private": "إنشاء ائتلاف خاص",
    "coalition_create_rules_hint": "مثال: نسبة المساهمة، شروط الاسترداد...",
    "coalition_create_rules_label": "قواعد الائتلاف (اختياري)",
    "coalition_create_success": "تم إنشاء الائتلاف بنجاح",
    "coalition_create_suggestions_title": "تجار مقترحون قريبون",
    "coalition_distance_km": "كم",
    "coalition_distance_unknown": "المسافة غير معروفة",
    "coalition_filter_all": "الكل",
    "coalition_filter_different_activity": "نشاط مختلف",
    "coalition_filter_same_activity": "نفس النشاط",
    "coalition_gift_campaign_new_acquisition": "حملة استقطاب عملاء جدد",
    "coalition_gift_campaign_standard": "حملة قياسية",
    "coalition_gift_campaign_type_label": "نوع الحملة",
    "coalition_gift_campaign_vip_loyalty": "حملة ولاء عملاء VIP",
    "coalition_gift_catalog_subtitle": "هدايا يمكن استردادها لدى أي عضو في الائتلاف",
    "coalition_gift_catalog_title": "كتالوج هدايا الائتلاف",
    "coalition_gift_create": "إنشاء هدية",
    "coalition_gift_create_button": "إنشاء الهدية",
    "coalition_gift_create_success": "تم إنشاء الهدية بنجاح",
    "coalition_gift_creating": "جارٍ الإنشاء...",
    "coalition_gift_description_hint": "وصف مختصر للهدية",
    "coalition_gift_description_label": "الوصف",
    "coalition_gift_discount_hint": "مثال: 10",
    "coalition_gift_discount_label": "نسبة الخصم %",
    "coalition_gift_expires_label": "تاريخ الانتهاء",
    "coalition_gift_max_days_label": "أقصى مدة (أيام)",
    "coalition_gift_min_frequency_hint": "الحد الأدنى لعدد الزيارات",
    "coalition_gift_min_frequency_label": "الحد الأدنى للتكرار",
    "coalition_gift_monetary_value_hint": "القيمة بالعملة",
    "coalition_gift_monetary_value_label": "القيمة المالية",
    "coalition_gift_no_gifts": "لا توجد هدايا بعد",
    "coalition_gift_points_hint": "النقاط المطلوبة للاسترداد",
    "coalition_gift_points_label": "النقاط المطلوبة",
    "coalition_gift_quantity_hint": "الكمية المتاحة",
    "coalition_gift_quantity_label": "الكمية",
    "coalition_gift_target_new_customers": "استهداف العملاء الجدد",
    "coalition_gift_target_vip_customers": "استهداف عملاء VIP",
    "coalition_gift_targeting_new": "عملاء جدد",
    "coalition_gift_targeting_title": "الاستهداف",
    "coalition_gift_targeting_vip": "عملاء VIP",
    "coalition_gift_title_hint": "مثال: قهوة مجانية",
    "coalition_gift_title_label": "عنوان الهدية",
    "coalition_impact_as_contributor": "كمساهم",
    "coalition_impact_as_fulfiller": "كمنفذ",
    "coalition_impact_cross_customers": "العملاء المتقاطعون",
    "coalition_impact_no_cross_customers": "لا يوجد عملاء متقاطعون بعد",
    "coalition_impact_refresh": "تحديث",
    "coalition_impact_report_title": "تقرير أثر الائتلاف",
    "coalition_invitations_empty": "لا توجد دعوات معلقة",
    "coalition_join_request": "طلب انضمام",
    "coalition_join_request_confirmed": "تم إرسال طلب الانضمام بنجاح",
    "coalition_joined": "تم الانضمام",
    "coalition_label": "الائتلاف",
    "coalition_merchant_generic": "تاجر",
    "coalition_my_empty": "لم تنضم إلى أي ائتلاف بعد",
    "coalition_private_discover_empty": "لا توجد ائتلافات خاصة متاحة حالياً",
    "coalition_public_activate_button": "فعّل العضوية العامة",
    "coalition_public_active_badge": "نشط",
    "coalition_public_apply_button": "تقديم طلب",
    "coalition_public_description": "انضم إلى الشبكة العامة ليتمكن عملاء جميع الأعضاء من كسب النقاط واستردادها لديك",
    "coalition_public_header": "الائتلاف العام",
    "coalition_public_membership_details": "تفاصيل العضوية",
    "coalition_region_global": "عالمي",
    "coalition_reject": "رفض",
    "coalition_screen_title": "الائتلافات",
    "coalition_sending": "جارٍ الإرسال...",
    "coalition_status_active": "نشط",
    "coalition_status_inactive": "غير نشط",
    "coalition_suggestions_empty": "لا توجد اقتراحات حالياً",
    "coalition_suggestions_load_failed": "تعذر تحميل الاقتراحات",
    "coalition_tab_active": "ائتلافاتي",
    "coalition_tab_discover": "استكشاف",
    "coalition_tab_invitations": "الدعوات",
    "coalition_unknown": "غير معروف",
    "coalition_untitled": "ائتلاف بدون اسم",
    "confirm": "تأكيد",
    "merchant_branch_active": "الفرع نشط",
    "merchant_branch_active_hint": "الفرع ظاهر للعملاء ويستقبل الطلبات",
    "merchant_branch_inactive_hint": "الفرع مخفي مؤقتاً عن العملاء",
    "merchant_gifting_auto_trigger_description": "أرسل هدية تلقائياً عند وصول العميل إلى حد النقاط المحدد",
    "merchant_gifting_auto_trigger_title": "المحفز التلقائي للهدايا",
    "merchant_gifting_example_message": "تهانينا! حصلت على هدية من متجرنا، تفضل بزيارتنا لاستلامها",
    "merchant_gifting_example_message_title": "مثال على رسالة الهدية",
    "merchant_gifting_flow_line_1": "يجمع العميل نقاطاً من مشترياته",
    "merchant_gifting_flow_line_2": "عند بلوغ الحد يعمل المحفز تلقائياً",
    "merchant_gifting_flow_line_3": "تُرسل الهدية إلى محفظة العميل",
    "merchant_gifting_flow_line_4": "يسترد العميل الهدية في متجرك",
    "merchant_gifting_flow_title": "كيف تسير العملية",
    "merchant_gifting_how_step_1": "حدّد عدد النقاط المطلوب",
    "merchant_gifting_how_step_2": "فعّل المحفز التلقائي",
    "merchant_gifting_how_step_3": "راقب الهدايا المرسلة من السجل",
    "merchant_gifting_how_step_4": "عدّل الحد في أي وقت",
    "merchant_gifting_how_title": "كيف تستخدم محفز الهدايا؟",
    "merchant_gifting_invalid_threshold": "أدخل عدد نقاط صحيحاً أكبر من صفر",
    "merchant_gifting_required_points": "النقاط المطلوبة",
    "merchant_gifting_required_points_hint": "مثال: 500",
    "merchant_gifting_save_trigger": "حفظ المحفز",
    "merchant_gifting_saved": "تم حفظ المحفز بنجاح",
    "merchant_gifting_saving": "جارٍ الحفظ...",
    "merchant_gifting_screen_title": "هدايا التاجر",
    "merchant_nav_clearinghouse": "غرفة المقاصة",
    "merchant_nav_coalitions": "الائتلافات",
    "merchant_nav_gifting": "الهدايا",
    "merchant_pending_points_title": "النقاط المعلقة",
    "merchant_team_open_hint": "إدارة أعضاء الفريق والصلاحيات",
    "merchant_team_title": "فريق العمل",
    "merchant_token_wallet_open": "فتح محفظة الرموز",
    "settlement_dispute_reject": "رفض النزاع",
    "settlement_dispute_resolve": "حل النزاع",
    "settlement_dispute_response": "الرد على النزاع",
}

EN = {
    "clearinghouse_action": "Action",
    "clearinghouse_date": "Date",
    "clearinghouse_detailed_ledger": "Detailed ledger",
    "clearinghouse_from": "From",
    "clearinghouse_how_step_1": "Review the issued vs redeemed points summary across coalition members",
    "clearinghouse_how_step_2": "Check the net balance owed to each member",
    "clearinghouse_how_step_3": "Tap Settle to confirm the net transfer between members",
    "clearinghouse_how_step_4": "The confirmed settlement appears in the detailed ledger",
    "clearinghouse_how_title": "How to use the clearinghouse",
    "clearinghouse_internal_only_disclosure": "This data is internal to coalition members only and is never shown to customers",
    "clearinghouse_net": "Net",
    "clearinghouse_no_ledger": "No ledger entries yet",
    "clearinghouse_refresh": "Refresh",
    "clearinghouse_settle": "Settle",
    "clearinghouse_settlement_confirmed": "Settlement confirmed successfully",
    "clearinghouse_summary_cross_redemptions": "Cross redemptions",
    "clearinghouse_summary_net_balance": "Net balance",
    "clearinghouse_summary_points_issued": "Points issued",
    "clearinghouse_to": "To",
    "coalition_accept": "Accept",
    "coalition_activity_unknown": "Unknown activity",
    "coalition_cancel": "Cancel",
    "coalition_create_and_invite": "Create & invite",
    "coalition_create_help": "Create a private coalition and invite nearby merchants to join",
    "coalition_create_invitees_hint": "Enter merchant ID or phone number",
    "coalition_create_invitees_label": "Invitees",
    "coalition_create_invitees_range": "You can invite 1 to 10 merchants",
    "coalition_create_missing_id": "Enter a merchant ID first",
    "coalition_create_name_label": "Coalition name",
    "coalition_create_name_required": "Coalition name is required",
    "coalition_create_private": "Create private coalition",
    "coalition_create_rules_hint": "e.g. contribution rate, redemption rules...",
    "coalition_create_rules_label": "Coalition rules (optional)",
    "coalition_create_success": "Coalition created successfully",
    "coalition_create_suggestions_title": "Suggested nearby merchants",
    "coalition_distance_km": "km",
    "coalition_distance_unknown": "Distance unknown",
    "coalition_filter_all": "All",
    "coalition_filter_different_activity": "Different activity",
    "coalition_filter_same_activity": "Same activity",
    "coalition_gift_campaign_new_acquisition": "New customer acquisition campaign",
    "coalition_gift_campaign_standard": "Standard campaign",
    "coalition_gift_campaign_type_label": "Campaign type",
    "coalition_gift_campaign_vip_loyalty": "VIP loyalty campaign",
    "coalition_gift_catalog_subtitle": "Gifts redeemable at any coalition member",
    "coalition_gift_catalog_title": "Coalition gift catalog",
    "coalition_gift_create": "Create gift",
    "coalition_gift_create_button": "Create gift",
    "coalition_gift_create_success": "Gift created successfully",
    "coalition_gift_creating": "Creating...",
    "coalition_gift_description_hint": "Short gift description",
    "coalition_gift_description_label": "Description",
    "coalition_gift_discount_hint": "e.g. 10",
    "coalition_gift_discount_label": "Discount %",
    "coalition_gift_expires_label": "Expiry date",
    "coalition_gift_max_days_label": "Max duration (days)",
    "coalition_gift_min_frequency_hint": "Minimum visit count",
    "coalition_gift_min_frequency_label": "Minimum frequency",
    "coalition_gift_monetary_value_hint": "Value in currency",
    "coalition_gift_monetary_value_label": "Monetary value",
    "coalition_gift_no_gifts": "No gifts yet",
    "coalition_gift_points_hint": "Points required to redeem",
    "coalition_gift_points_label": "Required points",
    "coalition_gift_quantity_hint": "Available quantity",
    "coalition_gift_quantity_label": "Quantity",
    "coalition_gift_target_new_customers": "Target new customers",
    "coalition_gift_target_vip_customers": "Target VIP customers",
    "coalition_gift_targeting_new": "New customers",
    "coalition_gift_targeting_title": "Targeting",
    "coalition_gift_targeting_vip": "VIP customers",
    "coalition_gift_title_hint": "e.g. Free coffee",
    "coalition_gift_title_label": "Gift title",
    "coalition_impact_as_contributor": "As contributor",
    "coalition_impact_as_fulfiller": "As fulfiller",
    "coalition_impact_cross_customers": "Cross customers",
    "coalition_impact_no_cross_customers": "No cross customers yet",
    "coalition_impact_refresh": "Refresh",
    "coalition_impact_report_title": "Coalition impact report",
    "coalition_invitations_empty": "No pending invitations",
    "coalition_join_request": "Join request",
    "coalition_join_request_confirmed": "Join request sent successfully",
    "coalition_joined": "Joined",
    "coalition_label": "Coalition",
    "coalition_merchant_generic": "Merchant",
    "coalition_my_empty": "You have not joined any coalition yet",
    "coalition_private_discover_empty": "No private coalitions available right now",
    "coalition_public_activate_button": "Activate public membership",
    "coalition_public_active_badge": "Active",
    "coalition_public_apply_button": "Apply",
    "coalition_public_description": "Join the public network so customers of all members can earn and redeem points with you",
    "coalition_public_header": "Public coalition",
    "coalition_public_membership_details": "Membership details",
    "coalition_region_global": "Global",
    "coalition_reject": "Reject",
    "coalition_screen_title": "Coalitions",
    "coalition_sending": "Sending...",
    "coalition_status_active": "Active",
    "coalition_status_inactive": "Inactive",
    "coalition_suggestions_empty": "No suggestions right now",
    "coalition_suggestions_load_failed": "Failed to load suggestions",
    "coalition_tab_active": "My coalitions",
    "coalition_tab_discover": "Discover",
    "coalition_tab_invitations": "Invitations",
    "coalition_unknown": "Unknown",
    "coalition_untitled": "Untitled coalition",
    "confirm": "Confirm",
    "merchant_branch_active": "Branch active",
    "merchant_branch_active_hint": "Branch is visible to customers and accepting orders",
    "merchant_branch_inactive_hint": "Branch is temporarily hidden from customers",
    "merchant_gifting_auto_trigger_description": "Automatically send a gift when a customer reaches the points threshold",
    "merchant_gifting_auto_trigger_title": "Automatic gift trigger",
    "merchant_gifting_example_message": "Congratulations! You received a gift from our store, visit us to claim it",
    "merchant_gifting_example_message_title": "Gift message example",
    "merchant_gifting_flow_line_1": "Customer earns points from purchases",
    "merchant_gifting_flow_line_2": "The trigger fires when the threshold is reached",
    "merchant_gifting_flow_line_3": "The gift is sent to the customer's wallet",
    "merchant_gifting_flow_line_4": "Customer redeems the gift in your store",
    "merchant_gifting_flow_title": "How the flow works",
    "merchant_gifting_how_step_1": "Set the required points threshold",
    "merchant_gifting_how_step_2": "Enable the automatic trigger",
    "merchant_gifting_how_step_3": "Monitor sent gifts from the log",
    "merchant_gifting_how_step_4": "Adjust the threshold anytime",
    "merchant_gifting_how_title": "How to use the gift trigger",
    "merchant_gifting_invalid_threshold": "Enter a valid points threshold greater than zero",
    "merchant_gifting_required_points": "Required points",
    "merchant_gifting_required_points_hint": "e.g. 500",
    "merchant_gifting_save_trigger": "Save trigger",
    "merchant_gifting_saved": "Trigger saved successfully",
    "merchant_gifting_saving": "Saving...",
    "merchant_gifting_screen_title": "Merchant gifting",
    "merchant_nav_clearinghouse": "Clearinghouse",
    "merchant_nav_coalitions": "Coalitions",
    "merchant_nav_gifting": "Gifting",
    "merchant_pending_points_title": "Pending points",
    "merchant_team_open_hint": "Manage team members and permissions",
    "merchant_team_title": "Team",
    "merchant_token_wallet_open": "Open token wallet",
    "settlement_dispute_reject": "Reject dispute",
    "settlement_dispute_resolve": "Resolve dispute",
    "settlement_dispute_response": "Dispute response",
}

def append_keys(path, new):
    with open(path, encoding="utf-8") as f:
        text = f.read()
    data = json.loads(text)
    added = {k: v for k, v in new.items() if k not in data}
    if not added:
        print(f"{path}: nothing to add")
        return
    stripped = text.rstrip()
    assert stripped.endswith("}"), path
    body = stripped[:-1].rstrip()
    assert not body.endswith(","), path
    lines = [","]
    items = list(added.items())
    for i, (k, v) in enumerate(items):
        suffix = "," if i < len(items) - 1 else ""
        lines.append(f"  {json.dumps(k, ensure_ascii=False)}: {json.dumps(v, ensure_ascii=False)}{suffix}")
    out = body + "\n".join(lines) + "\n}\n"
    with open(path, "w", encoding="utf-8") as f:
        f.write(out)
    json.loads(out)  # validate
    print(f"{path}: added {len(added)} keys (total {len(data) + len(added)})")

append_keys("assets/lang/ar.json", AR)
append_keys("assets/lang/en.json", EN)
